package com.example.demo.utils;

import com.example.demo.entity.ReceivedMessage;
import org.springframework.http.*;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class Utils {

    public static Map<String, String> LOCATIONS = new HashMap<>();

    private static final String pattern = "yyyy-MM-dd";
    private static final DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern(pattern);
    private static final SimpleDateFormat sdf = new SimpleDateFormat(pattern);

    public static Map<String, String> MONTHS = new HashMap<>();

    public static String[] SHORTNAME = {
            "KBL",
            "TIA",
            "ALG",
            "LUA",
            "BNS",
            "YRV",
            "MLB",
            "PRT",
            "SYD",
            "VNN",
            "BKU",
            "NSS",
            "MNA",
            "DHK",
            "BGN",
            "MSK",
            "BRS",
            "BLZ",
            "COT",
            "HML",
            "LPZ",
            "SAR",
            "GAB",
            "BRA",
            "PTA",
            "RCF",
            "RDJ",
            "SPL",
            "BSB",
            "SOF",
            "OUG",
            "RNG",
            "BUJ",
            "PIA",
            "PHP",
            "YDE",
            "CLG",
            "HLF",
            "MTL",
            "OTT",
            "QBC",
            "TRT",
            "VAC",
            "NDJ",
            "SNT",
            "BEJ",
            "CHE",
            "GUZ",
            "SHG",
            "SNY",
            "BGT",
            "BRZ",
            "KIN",
            "SNJ",
            "ABJ",
            "ZGB",
            "HAV",
            "CRC",
            "NCS",
            "PRG",
            "CPN",
            "DJI",
            "SDO",
            "GYQ",
            "QTO",
            "CRO",
            "SNS",
            "LND",
            "MBO",
            "ASM",
            "TAL",
            "MBA",
            "ADD",
            "SUV",
            "HLS",
            "PRS",
            "LIB",
            "BAN",
            "TBL",
            "BRL",
            "FRN",
            "MUN",
            "ACC",
            "ATH",
            "GTM",
            "CRY",
            "GEO",
            "PTP",
            "TGG",
            "HNK",
            "BDP",
            "RKJ",
            "MDR",
            "HYD",
            "CLC",
            "BMB",
            "NWD",
            "JAK",
            "SRB",
            "BGH",
            "ERB",
            "DBL",
            "TLV",
            "FLR",
            "MLN",
            "NPL",
            "RME",
            "KNG",
            "FKK",
            "NHA",
            "KBO",
            "SPP",
            "TKY",
            "JRS",
            "AMM",
            "ATA",
            "AST",
            "NRB",
            "PRI",
            "KWT",
            "BKK",
            "VNT",
            "RGA",
            "BRT",
            "MAS",
            "MRV",
            "VIL",
            "LXM",
            "ANT",
            "LIL",
            "KLL",
            "BAM",
            "VLL",
            "MAJ",
            "NUK",
            "PTL",
            "CDJ",
            "GDL",
            "HER",
            "MTM",
            "MER",
            "MEX",
            "MTR",
            "NGL",
            "NVL",
            "TJT",
            "KOL",
            "CHS",
            "ULN",
            "POD",
            "CSB",
            "MAP",
            "WHK",
            "KDU",
            "AMS",
            "USN",
            "ACK",
            "MNG",
            "NMY",
            "ABU",
            "LGS",
            "SKO",
            "BLF",
            "OSL",
            "MST",
            "ISL",
            "KRC",
            "KOR",
            "PNM",
            "PTM",
            "ASN",
            "LMA",
            "MNL",
            "KRK",
            "WRW",
            "LSB",
            "DOH",
            "BCH",
            "MOS",
            "VLA",
            "YEK",
            "KGL",
            "APA",
            "DHR",
            "JDD",
            "RID",
            "DKR",
            "BLG",
            "FTN",
            "SGP",
            "BTS",
            "LJU",
            "CPT",
            "DRB",
            "JHN",
            "SEO",
            "JBA",
            "MDD",
            "CLM",
            "KHT",
            "PRM",
            "STK",
            "BEN",
            "TAI",
            "DHB",
            "DRS",
            "BNK",
            "CHN",
            "DIL",
            "LOM",
            "PTS",
            "TNS",
            "ANK",
            "IST",
            "AKD",
            "KMP",
            "KEV",
            "ABD",
            "DUB",
            "MTV",
            "THT",
            "HAN",
            "HCM",
            "DPT",
            "LUS",
            "HRE"
    };

    public static String[] FULLNAME = {
            "AFGHANISTAN, KABUL",
            "ALBANIA, TIRANA",
            "ALGERIA, ALGIERS",
            "ANGOLA, LUANDA",
            "ARGENTINA, BUENOS AIRES",
            "ARMENIA, YEREVAN",
            "AUSTRALIA, MELBOURNE",
            "AUSTRALIA, PERTH",
            "AUSTRALIA, SYDNEY",
            "AUSTRIA, VIENNA",
            "AZERBAIJAN, BAKU",
            "BAHAMAS, NASSAU",
            "BAHRAIN, MANAMA",
            "BANGLADESH, DHAKA",
            "BARBADOS, BRIDGETOWN",
            "BELARUS, MINSK",
            "BELGIUM, BRUSSELS",
            "BELIZE, BELMOPAN",
            "BENIN, COTONOU",
            "BERMUDA, HAMILTON",
            "BOLIVIA, LA PAZ",
            "BOSNIA-HERZEGOVINA, SARAJEVO",
            "BOTSWANA, GABORONE",
            "BRAZIL, BRASILIA",
            "BRAZIL, PORTO ALEGRE",
            "BRAZIL, RECIFE",
            "BRAZIL, RIO DE JANEIRO",
            "BRAZIL, SAO PAULO",
            "BRUNEI, BANDAR SERI BEGAWAN",
            "BULGARIA, SOFIA",
            "BURKINA FASO, OUAGADOUGOU",
            "BURMA, RANGOON",
            "BURUNDI, BUJUMBURA",
            "CABO VERDE, PRAIA",
            "CAMBODIA, PHNOM PENH",
            "CAMEROON, YAOUNDE",
            "CANADA, CALGARY",
            "CANADA, HALIFAX",
            "CANADA, MONTREAL",
            "CANADA, OTTAWA",
            "CANADA, QUEBEC",
            "CANADA, TORONTO",
            "CANADA, VANCOUVER",
            "CHAD, N`DJAMENA",
            "CHILE, SANTIAGO",
            "CHINA, BEIJING",
            "CHINA, CHENGDU",
            "CHINA, GUANGZHOU",
            "CHINA, SHANGHAI",
            "CHINA, SHENYANG",
            "COLOMBIA, BOGOTA",
            "CONGO, BRAZZAVILLE",
            "CONGO, KINSHASA",
            "COSTA RICA, SAN JOSE",
            "COTE D`IVORIE, ABIDJAN",
            "CROATIA, ZAGREB",
            "CUBA, HAVANA",
            "CURACAO, CURACAO",
            "CYPRUS, NICOSIA",
            "CZECH REPUBLIC, PRAGUE",
            "DENMARK, COPENHAGEN",
            "DJIBOUTI, DJIBOUTI",
            "DOMINICAN REPUBLIC, SANTO DOMINGO",
            "ECUADOR, GUAYAQUIL",
            "ECUADOR, QUITO",
            "EGYPT, CAIRO",
            "EL SALVADOR, SAN SALVADOR",
            "ENGLAND, LONDON",
            "EQUATORIAL GUINEA, MALABO",
            "ERITREA, ASMARA",
            "ESTONIA, TALLINN",
            "ESWATINI, MBABANE",
            "ETHIOPIA, ADDIS ABABA",
            "FIJI, SUVA",
            "FINLAND, HELSINKI",
            "FRANCE, PARIS",
            "GABON, LIBREVILLE",
            "GAMBIA, BANJUL",
            "GEORGIA, TBILISI",
            "GERMANY, BERLIN",
            "GERMANY, FRANKFURT",
            "GERMANY, MUNICH",
            "GHANA, ACCRA",
            "GREECE, ATHENS",
            "GUATEMALA, GUATEMALA CITY",
            "GUINEA, CONAKRY",
            "GUYANA, GEORGETOWN",
            "HAITI, PORT-AU-PRINCE",
            "HONDURAS, TEGUCIGALPA",
            "HONG KONG",
            "HUNGARY, BUDAPEST",
            "ICELAND, REYKJAVIK",
            "INDIA, CHENNAI",
            "INDIA, HYDERABAD",
            "INDIA, KOLKATA",
            "INDIA, MUMBAI",
            "INDIA, NEW DELHI",
            "INDONESIA, JAKARTA",
            "INDONESIA, SURABAYA",
            "IRAQ, BAGHDAD",
            "IRAQ, ERBIL",
            "IRELAND, DUBLIN",
            "ISRAEL, TEL AVIV",
            "ITALY, FLORENCE",
            "ITALY, MILAN",
            "ITALY, NAPLES",
            "ITALY, ROME",
            "JAMAICA, KINGSTON",
            "JAPAN, FUKUOKA",
            "JAPAN, NAHA",
            "JAPAN, OSAKA",
            "JAPAN, SAPPORO",
            "JAPAN, TOKYO",
            "JERUSALEM",
            "JORDAN, AMMAN",
            "KAZAKHSTAN, ALMATY",
            "KAZAKHSTAN, ASTANA",
            "KENYA, NAIROBI",
            "KOSOVO, PRISTINA",
            "KUWAIT, KUWAIT CITY",
            "KYRGYZSTAN, BISHKEK",
            "LAOS, VIENTIANE",
            "LATVIA, RIGA",
            "LEBANON, BEIRUT",
            "LESOTHO, MASERU",
            "LIBERIA, MONROVIA",
            "LITHUANIA, VILNIUS",
            "LUXEMBOURG, LUXEMBOURG",
            "MADAGASCAR, ANTANANARIVO",
            "MALAWI, LILONGWE",
            "MALAYSIA, KUALA LUMPUR",
            "MALI, BAMAKO",
            "MALTA, VALLETTA",
            "MARSHALL ISLANDS, MAJURO",
            "MAURITANIA, NOUAKCHOTT",
            "MAURITIUS, PORT LOUIS",
            "MEXICO, CIUDAD JUAREZ",
            "MEXICO, GUADALAJARA",
            "MEXICO, HERMOSILLO",
            "MEXICO, MATAMOROS",
            "MEXICO, MERIDA",
            "MEXICO, MEXICO CITY",
            "MEXICO, MONTERREY",
            "MEXICO, NOGALES",
            "MEXICO, NUEVO LAREDO",
            "MEXICO, TIJUANA",
            "MICRONESIA, KOLONIA",
            "MOLDOVA, CHISINAU",
            "MONGOLIA, ULAANBAATAR",
            "MONTENEGRO, PODGORICA",
            "MOROCCO, CASABLANCA",
            "MOZAMBIQUE, MAPUTO",
            "NAMIBIA, WINDHOEK",
            "NEPAL, KATHMANDU",
            "NETHERLANDS, AMSTERDAM",
            "NEW YORK, NY - USA",
            "NEW ZEALAND, AUCKLAND",
            "NICARAGUA, MANAGUA",
            "NIGER, NIAMEY",
            "NIGERIA, ABUJA",
            "NIGERIA, LAGOS",
            "NORTH MACEDONIA, SKOPJE",
            "NORTHERN IRELAND, BELFAST",
            "NORWAY, OSLO",
            "OMAN, MUSCAT",
            "PAKISTAN, ISLAMABAD",
            "PAKISTAN, KARACHI",
            "PALAU, KOROR",
            "PANAMA, PANAMA CITY",
            "PAPUA NEW GUINEA, PORT MORESBY",
            "PARAGUAY, ASUNCION",
            "PERU, LIMA",
            "PHILIPPINES, MANILA",
            "POLAND, KRAKOW",
            "POLAND, WARSAW",
            "PORTUGAL, LISBON",
            "QATAR, DOHA",
            "ROMANIA, BUCHAREST",
            "RUSSIA, MOSCOW",
            "RUSSIA, VLADIVOSTOK",
            "RUSSIA, YEKATERINBURG",
            "RWANDA, KILGALI",
            "SAMOA, APIA",
            "SAUDI ARABIA, DHAHRAN",
            "SAUDI ARABIA, JEDDAH",
            "SAUDI ARABIA, RIYADH",
            "SENEGAL, DAKAR",
            "SERBIA, BELGRADE",
            "SIERRA LEONE, FREETOWN",
            "SINGAPORE, SINGAPORE",
            "SLOVAKIA, BRATISLAVA",
            "SLOVENIA, LJUBLJANA",
            "SOUTH AFRICA, CAPE TOWN",
            "SOUTH AFRICA, DURBAN",
            "SOUTH AFRICA, JOHANNESBURG",
            "SOUTH KOREA, SEOUL",
            "SOUTH SUDAN, JUBA",
            "SPAIN, MADRID",
            "SRI LANKA, COLOMBO",
            "SUDAN, KHARTOUM",
            "SURINAME, PARAMARIBO",
            "SWEDEN, STOCKHOLM",
            "SWITZERLAND, BERN",
            "TAIWAN, TAIPEI",
            "TAJIKISTAN, DUSHANBE",
            "TANZANIA, DAR ES SALAAM",
            "THAILAND, BANGKOK",
            "THAILAND, CHIANG MAI",
            "TIMOR LESTE, DILI",
            "TOGO, LOME",
            "TRINIDAD, PORT OF SPAIN",
            "TUNISIA, TUNIS",
            "TURKEY, ANKARA",
            "TURKEY, ISTANBUL",
            "TURKMENISTAN, ASHGABAT",
            "UGANDA, KAMPALA",
            "UKRAINE, KYIV",
            "UNITED ARAB EMIRATES, ABU DHABI",
            "UNITED ARAB EMIRATES, DUBAI",
            "URUGUAY, MONTEVIDEO",
            "UZBEKISTAN, TASHKENT",
            "VIETNAM, HANOI",
            "VIETNAM, HO CHI MINH CITY",
            "WASHINGTON, DC - USA",
            "ZAMBIA, LUSAKA",
            "ZIMBABWE, HARARE"
    };

    static {
        for(int i = 0; i < SHORTNAME.length; i++) {
            LOCATIONS.put(FULLNAME[i], SHORTNAME[i]);
        }

        MONTHS.put("Jan", "01");
        MONTHS.put("Feb", "02");
        MONTHS.put("Mar", "03");
        MONTHS.put("Apr", "04");
        MONTHS.put("May", "05");
        MONTHS.put("Jun", "06");
        MONTHS.put("Jul", "07");
        MONTHS.put("Aug", "08");
        MONTHS.put("Sept", "09");
        MONTHS.put("Sep", "09");
        MONTHS.put("Oct", "10");
        MONTHS.put("Nov", "11");
        MONTHS.put("Dec", "12");
    }

    public static ReceivedMessage sendPostRequest(String url, MultiValueMap<String, String> params) {
        RestTemplate client = new RestTemplate();
        HttpHeaders headers = new HttpHeaders();
        HttpMethod method = HttpMethod.POST;
        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
        HttpEntity<MultiValueMap<String, String>> requestEntity = new HttpEntity<>(params, headers);
        ResponseEntity<ReceivedMessage> response = client.exchange(url, method, requestEntity, ReceivedMessage.class);
        return response.getBody();
    }

    public static String getAutoExpirationDate(String interviewDate) {
        Calendar cal = Calendar.getInstance();
        String autoExpirationDate = null;
        try {
            Date date = sdf.parse(interviewDate);
            cal.setTime(date);
            cal.add(Calendar.MONTH, 6);
            autoExpirationDate = sdf.format(cal.getTime());

        } catch(Exception e) {

        }
        return autoExpirationDate;
    }

    public static String convertDateToRightFormat(String date) {
        String[] dayMonthYear = date.split("-");
        if(dayMonthYear.length != 3) return "2001-01-01";
        dayMonthYear[1] = MONTHS.get(dayMonthYear[1]);
        return dayMonthYear[2] + "-" + dayMonthYear[1] + "-" + dayMonthYear[0];
    }

    public static String getDateOfToday() {
        Date date = new Date();
        return sdf.format(date);
    }
}
