spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        username: visastatus_info
        password: 4wKmRHwE5PF22ik4
        url: jdbc:mariadb://localhost:3306/visastatus_info

    mail:
        host: smtp.ionos.com
        port: 587
        username: admin@visastatus.info
        password: gy569706
        protocol: smtp
        properties.mail.smtp:
            auth: true
            starttls.enable: true

logging:
    file.name: logs/visastatus.log
    level:
        root: info


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.demo.entity

bucket4j:
    enabled: true
    filters:
        - cache-name: buckets
          url: /casehistory/list
          rate-limits:
              - bandwidths:
                    - capacity: 30
                      time: 3
                      unit: HOURS