package com.example.demo.entity;

import java.util.Objects;

public class Case {
    private String cid;         //case id
    private int id;          //id generated by database
    private String location;     //where you were interviewed
    private String category;    //the visa category you applied
    private boolean done;       //is your case done
    private String isSTEM;      //is your major one of the STEM majors?
    private String isUniversitySensitive;   //is the university you graduated very sensitive? e.g., regulated by pp10043
    private String interviewDate;   //when did the interview happen?
    private String notes;       //something you want to say about the interview
    private String autoRefreshExpireDate;   //when will the auto refresh service expire
    private String status;      //current status from Ceac.state.gov

    private String updatedDate;
    private String email;

    private String passportID;      //passport ID is required when querying status
    private String surname;         //surname is required when querying status

    public Case() {
    }

    public Case(String cid, int id, String location, String category, boolean done, String isSTEM, String isUniversitySensitive, String interviewDate, String notes, String autoRefreshExpireDate, String status, String updatedDate, String email, String passportID, String surname) {
        this.cid = cid;
        this.id = id;
        this.location = location;
        this.category = category;
        this.done = done;
        this.isSTEM = isSTEM;
        this.isUniversitySensitive = isUniversitySensitive;
        this.interviewDate = interviewDate;
        this.notes = notes;
        this.autoRefreshExpireDate = autoRefreshExpireDate;
        this.status = status;
        this.updatedDate = updatedDate;
        this.email = email;
        this.passportID = passportID;
        this.surname = surname;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public boolean isDone() {
        return done;
    }

    public void setDone(boolean done) {
        this.done = done;
    }

    public String getIsSTEM() {
        return isSTEM;
    }

    public void setIsSTEM(String isSTEM) {
        this.isSTEM = isSTEM;
    }

    public String getIsUniversitySensitive() {
        return isUniversitySensitive;
    }

    public void setIsUniversitySensitive(String isUniversitySensitive) {
        this.isUniversitySensitive = isUniversitySensitive;
    }

    public String getInterviewDate() {
        return interviewDate;
    }

    public void setInterviewDate(String interviewDate) {
        this.interviewDate = interviewDate;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getAutoRefreshExpireDate() {
        return autoRefreshExpireDate;
    }

    public void setAutoRefreshExpireDate(String autoRefreshExpireDate) {
        this.autoRefreshExpireDate = autoRefreshExpireDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(String updatedDate) {
        this.updatedDate = updatedDate;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassportID() {
        return passportID;
    }

    public void setPassportID(String passportID) {
        this.passportID = passportID;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public void hidePersonalInfo() {
        cid = "";
        email = "";
        passportID = "";
        surname = "";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Case aCase = (Case) o;
        return cid.equals(aCase.cid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cid);
    }


    @Override
    public String toString() {
        return "Case{" +
                "cid='" + cid + '\'' +
                ", id=" + id +
                ", location='" + location + '\'' +
                ", category='" + category + '\'' +
                ", done=" + done +
                ", isSTEM='" + isSTEM + '\'' +
                ", isUniversitySensitive='" + isUniversitySensitive + '\'' +
                ", interviewDate='" + interviewDate + '\'' +
                ", notes='" + notes + '\'' +
                ", autoRefreshExpireDate='" + autoRefreshExpireDate + '\'' +
                ", status='" + status + '\'' +
                ", updatedDate='" + updatedDate + '\'' +
                ", email='" + email + '\'' +
                ", passportID='" + passportID + '\'' +
                ", surname='" + surname + '\'' +
                '}';
    }
}
